Changed Composer Install script.
Signed-off-by: Rahul Prajapati <rahul.prajapati@live.in>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -297,8 +297,19 @@ function ee_install()
     || ee_lib_error "Unable to clone EasyEngine, exit status" $?
 
     cd /opt/easyengine
+
+    # Install Composer : https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
+    EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-    php -r "if (hash_file('SHA384', 'composer-setup.php') === 'aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
+    ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+
+    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+    then
+        >&2 echo 'ERROR: Invalid installer signature'
+        rm composer-setup.php
+        exit 1
+    fi
+
     php composer-setup.php
     php -r "unlink('composer-setup.php');"
     php composer.phar install || ee_lib_error "Unable to install EasyEngine, exit status " $?
